In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Position_Salaries.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.ensemble import RandomForestRegressor #ensemble is like taking multiple trees and getting avg from them
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0) #n_esti is number of trees taken
regressor.fit(x, y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [4]:
regressor.predict([[6.5]])

array([167000.])

np.arange(3,7)
array([3, 4, 5, 6])

np.arange(3,7,2)
array([3, 5])

In [5]:
x_grid = np.arange(min(x), max(x), 0.01)
x_grid = x_grid.reshape(len(x_grid),1)
plt.scatter(x, y, color = 'red')
plt.plot(x_grid, regressor.predict(x_grid), color = 'blue')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()

In [6]:
regressor.predict([[6.5]])

array([167000.])